service:
  info: Account Microservice (Development)
  version: 2.0-Beta

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dms
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9001

