service:
  name: customer
  info: Customer Microservice (DEVELOPMENT)
  version: 2.2-Beta

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/db_customer
    username: rtrpostgres
    password: 123

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8080/realms/rtr-ms

server:
  port: 9000